package com.Rohzek.util;

import com.Rohzek.lib.RefStrings;

import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

public class LoadMetaData 
{
	public LoadMetaData()
	{}
		
	public static void load(FMLPreInitializationEvent PreEvent)
	{
		ModMetadata  m = PreEvent.getModMetadata();
		
		m.autogenerated = false; //This is required otherwise it will not work
		
		m.modId = RefStrings.MODID;
		m.version = RefStrings.VERSION;
		m.name = RefStrings.NAME;
		m.url = "www.twitter.com/Rohzek";
		m.description = "Gurenn Lagann inspired mod";
		m.logoFile = RefStrings.RESOURCEID + "logo.png";
		LogHelper.debug("Our logo should be loaded from: " + RefStrings.RESOURCEID + ".png");
		m.authorList.add("Rohzek");
		
	}
}
